### ISSUE TITLE
👍 > 💩

### ISSUE THREAD

**Issue by shipmints** [positron-solutions/dslide#25]
;; Elisp has no random float because 💩

https://github.com/positron-solutions/dslide/blob/aa8aad225652217566fd0bb991e9eb946319220b/dslide.el#L2094

;; Elisp has cl-random float because 👍

https://github.com/emacs-mirror/emacs/blob/aaacd5806c75019b052a69764ef4d193d243573c/lisp/emacs-lisp/cl-extra.el#L460

https://www.gnu.org/software/emacs/manual/html_node/cl/Random-Numbers.html

**Comment by psionic-k** [comment]
Team CL represent :fist_raised:

**Comment by psionic-k** [comment]
Fixed in 710f54d79c30ee4e3aba96691f86c31e85520a45

Thanks!
