### ISSUE TITLE
Disable header

### ISSUE THREAD

**Issue by terlar** [positron-solutions/dslide#4]
Is there a way to disable the header? I couldn't find it.

**Comment by terlar** [comment]
I see you could do:
```
:PROPERTIES:
:DSLIDE_SLIDE_ACTION: dslide-slide-action-child :header nil
:END:
```

But would be nice to be able to opt-out globally without custom markup. Or perhaps it is just because things are wonky (#3) that I feel this way.

**Comment by psionic-k** [comment]
`dslide-header` was present but not supported.  The unstable branch contains a fix.

It is not yet possible to set `dslide-header` to false and override it with `:header nil`.  That is a separate issue that you may file if you encounter a need for it.

Please close if resolved.

**Comment by terlar** [comment]
Yeah, I can confirm that `dslide-header` with value `nil` seems to work now. Previously when I tried it, it didn't work.
